spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mymoney?serverTimezone=UTC
    username: root
    password: 123456
  main:
    banner-mode: off

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.tianyisoft.mymoney: debug


jwt:
  secret: "123456"